
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_HOST=redis_db
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=OAuth_demo
    depends_on:
      - redis_db
      - mysql_db

  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql_db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OAuth_demo
    ports:
      - "3306:3306"
